input:
  type: nats_stream
  nats_stream:
    ack_wait: 30s
    batching:
      byte_size: 0
      condition:
        type: static
        static: false
      count: 1
      period: ""
      processors: []
    client_id: otf_align_benthos_client
    cluster_id: test-cluster
    durable_name: #benthos_offset
    max_inflight: 1024
    queue: #benthos_queue
    start_from_oldest: true
    subject: otf.ingest
    unsubscribe_on_close: false
    urls:
      - nats://127.0.0.1:4222

pipeline:
  processors:
  - process_dag:

      brightpath_align:
          conditions:
            - bloblang: original.score.type() != "null" # ignore students with null score
          premap:
            alignMethod: meta.alignMethod
            alignToken: original.score
          processors:
            - http:
                parallel: true
                request:
                  url: http://localhost:1324/align
                  headers:
                    Content-Type: application/json
                  verb: POST
          postmap:
            otf.method: alignMethod
            otf.token: alignToken


      brightpath_map:
        dependencies:
          - otf.token # ensures align service has been called first
        conditions:
          - bloblang: this.meta.providerName == "BrightPath" # ensure is a brightpath record
        processors:
          - bloblang: |
              root = this
              otf.id.studentID = original.student_participation.enrolment.student.identifiers.0.identifier
              otf.id.studentGivenName = original.student_participation.enrolment.student.first_name
              otf.id.studentFamilyName = original.student_participation.enrolment.student.last_name

      lpofa_align:
          premap:
            alignMethod: meta.alignMethod
            alignToken: original.object.definition.name.en-US
          processors:
            - http:
                parallel: true
                request:
                  url: http://localhost:1324/align
                  headers:
                    Content-Type: application/json
                  verb: POST
          postmap:
            otf.method: alignMethod
            otf.token: alignToken

      lpofa_map:
        dependencies:
          - otf.token # ensures align service has been called first
        conditions:
          - bloblang: this.exists("original.actor.mbox") # xapi files only
        processors:
          - bloblang: |
              root = this
              otf.id.studentID = original.actor.mbox
              otf.id.studentFullName = original.actor.name

      mathspathway_align:
          premap:
            alignMethod: meta.alignMethod
            alignToken: original.module_id
          processors:
            - http:
                parallel: true
                request:
                  url: http://localhost:1324/align
                  headers:
                    Content-Type: application/json
                  verb: POST
          postmap:
            otf.method: alignMethod
            otf.token: alignToken

      mathspathway_map:
        dependencies:
          - otf.token # ensures align service has been called first
        conditions:
          - bloblang: this.meta.providerName == "MathsPathway" # ensure is a mathspathway record
        processors:
          - bloblang: |
              root = this
              otf.id.studentID = original.student_id
              # otf.id.studentFullName = "must be externally resolved"

      spa_align:
          premap:
            alignMethod: meta.alignMethod
            alignToken: original.TestCode
          processors:
            - http:
                parallel: true
                request:
                  url: http://localhost:1324/align
                  headers:
                    Content-Type: application/json
                  verb: POST
          postmap:
            otf.method: alignMethod
            otf.token: alignToken

      spa_map:
        dependencies:
          - otf.token # ensures align service has been called first
        conditions:
          - bloblang: this.meta.providerName == "SPA" # ensure is a sreams record
        processors:
          - bloblang: |
              root = this
              otf.id.studentID = original.StudentID
              otf.id.studentGivenName = original.FirstName
              otf.id.studentFamilyName = original.LastName
  
  - catch:
    - log:
        message: "Processing failed due to: ${!error()}"

output:
  files:
    path: ./msgs/${!count("files")}-${!timestamp_unix_nano()}.json
  processors:
    # don't save any files that did not get processed by the aligner
  - bloblang: |
      root = if !this.exists("otf.token") {
        deleted()
      }    







